[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "*", features = ["derive"] }
rstest = "0.23"
tracing = "0.1.4"
tracing-subscriber = "0.3"

[dev-dependencies]
tracing-test = "0.2"
